[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "surfmoss-tangods"
version = "0.1.0"
description = "Tango Device Servers for the SURFMOSS laboratory (IQFR-CSIC)"
requires-python = ">=3.9"
dependencies = ["pytango"]

[project.scripts]
# AGPolaritySwitch
AGPolaritySwitch = "AGPolaritySwitch:main"
# AMLPGC1
AMLPGC1 = "AMLPGC1:main"
# ArduinoDAC
ArduinoDAC = "ArduinoDAC:main"
# ArduinoMotor
ArduinoMotor = "ArduinoMotor:main"
# ArduinoPt
ArduinoPt = "ArduinoPt:main"
# BronkhorstMFC
MFC = "MFC:main"
# CryoCon32
CryoCon32 = "CryoCon32:main"
# ElmitecLEEM2k
ElmitecLEEM2k = "ElmitecLEEM2k:main"
# ElmitecUview
ElmitecUview = "ElmitecUview:main"
# FUGMCP
FUGMCP = "FUGMCP:main"
# HuttingerPFG-DC
HuttingerPFGDC = "HuttingerPFGDC:main"
# HuttingerPFG-RF
HuttingerPFGRF = "HuttingerPFGRF:main"
# Hygrometer
Hygrometer = "Hygrometer:main"
# Itech6000C
Itech6000C = "Itech6000C:main"
# LeyboldCenterOne
CenterOneGauge = "CenterOneGauge:main"
# LeyboldIG3
LeyboldIG3 = "LeyboldIG3:main"
# MKSGauge
MKSGauge = "MKSGauge:main"
# Motor
Motor = "Motor:main"
# NetworkUPSTools
NetworkUPSTool = "NetworkUPSTool:main"
# PIDController
PIDController = "PIDController:main"
# PfeifferHiScroll
PfeifferHiscroll = "PfeifferHiscroll:main"
# PfeifferTC100
PfeifferTC100 = "PfeifferTC100:main"
# PfeifferTU400
PfeifferTU400 = "PfeifferTU400:main"
# RaspberryButton
RaspberryButton = "RaspberryButton:main"
# RaspberrySwitch
RaspberrySwitch = "RaspberrySwitch:main"
# SEAWaterflowmeter
SEAWaterflowmeter = "SEAWaterflowmeter:main"
# SRIlockin830
SRIlockin830 = "SRIlockin830:main"
# TempSensorDS18B20
TempSensorDS18B20 = "TempSensorDS18B20:main"
# VarianTV301nav
VarianTV301nav = "VarianTV301nav:main"
# WaterSwitch
WaterSwitch = "WaterSwitch:main"
# tti604
Tti604 = "Tti604:main"

[tool.setuptools]
packages = [
    "AGPolaritySwitch",
    "AMLPGC1",
    "ArduinoDAC",
    "ArduinoMotor",
    "ArduinoPt",
    "CenterOneGauge",
    "CryoCon32",
    "ElmitecLEEM2k",
    "ElmitecUview",
    "FUGMCP",
    "HuttingerPFGDC",
    "HuttingerPFGRF",
    "Hygrometer",
    "Itech6000C",
    "LeyboldIG3",
    "MFC",
    "MKSGauge",
    "Motor",
    "NetworkUPSTool",
    "PIDController",
    "PfeifferHiscroll",
    "PfeifferTC100",
    "PfeifferTU400",
    "RaspberryButton",
    "RaspberrySwitch",
    "SEAWaterflowmeter",
    "SRIlockin830",
    "TempSensorDS18B20",
    "Tti604",
    "VarianTV301nav",
    "WaterSwitch",
]

[tool.setuptools.package-dir]
AGPolaritySwitch  = "AGPolaritySwitch/AGPolaritySwitch"
AMLPGC1           = "AMLPGC1/AMLPGC1"
ArduinoDAC        = "ArduinoDAC/ArduinoDAC"
ArduinoMotor      = "ArduinoMotor/ArduinoMotor"
ArduinoPt         = "ArduinoPt/ArduinoPt"
CenterOneGauge    = "CenterOneGauge/CenterOneGauge"
CryoCon32         = "CryoCon32/CryoCon32"
ElmitecLEEM2k     = "ElmitecLEEM2k/ElmitecLEEM2k"
ElmitecUview      = "ElmitecUview/ElmitecUview"
FUGMCP            = "FUGMCP/FUGMCP"
HuttingerPFGDC    = "HuttingerPFGDC/HuttingerPFGDC"
HuttingerPFGRF    = "HuttingerPFGRF/HuttingerPFGRF"
Hygrometer        = "Hygrometer/Hygrometer"
Itech6000C        = "Itech6000C/Itech6000C"
LeyboldIG3        = "LeyboldIG3/LeyboldIG3"
MFC               = "MFC/MFC"
MKSGauge          = "MKSGauge/MKSGauge"
Motor             = "Motor/Motor"
NetworkUPSTool    = "NetworkUPSTool/NetworkUPSTool"
PIDController     = "PIDController/PIDController"
PfeifferHiscroll  = "PfeifferHiscroll/PfeifferHiscroll"
PfeifferTC100     = "PfeifferTC100/PfeifferTC100"
PfeifferTU400     = "PfeifferTU400/PfeifferTU400"
RaspberryButton   = "RaspberryButton/RaspberryButton"
RaspberrySwitch   = "RaspberrySwitch/RaspberrySwitch"
SEAWaterflowmeter = "SEAWaterflowmeter/SEAWaterflowmeter"
SRIlockin830      = "SRIlockin830/SRIlockin830"
TempSensorDS18B20 = "TempSensorDS18B20/TempSensorDS18B20"
Tti604            = "Tti604/Tti604"
VarianTV301nav    = "VarianTV301nav/VarianTV301nav"
WaterSwitch       = "WaterSwitch/WaterSwitch"

[tool.setuptools.package-data]
"*" = ["*.xmi", "*.rst", "*.md"]
